export const muiDefaultArgsByComponent = {
  Alert: { severity: 'info', children: 'Alert message' },
  Avatar: { children: 'AV' },
  AvatarGroup: { max: 4 },
  Badge: { badgeContent: 4, children: ' ' },
  Box: { children: 'Box content' },
  Breadcrumbs: { children: 'Breadcrumbs content' },
  Button: { variant: 'contained', children: 'Button' },
  ButtonGroup: { variant: 'contained' },
  Card: { children: 'Card content' },
  CardActionArea: {},
  CardActions: {},
  CardContent: {},
  CardHeader: { title: 'Card Header', subheader: 'Subheader' },
  CardMedia: {
    component: 'img',
    height: '160',
    image: 'https://picsum.photos/seed/atoms-media/640/320',
    alt: 'Card media',
  },
  Checkbox: { checked: false },
  Chip: { label: 'Chip' },
  CircularProgress: { size: 28 },
  Container: { children: 'Container content' },
  Divider: {},
  Drawer: { open: true },
  FormControl: {},
  FormControlLabel: { label: 'Label' },
  FormGroup: {},
  FormHelperText: { children: 'Helper text' },
  FormLabel: { children: 'Label' },
  Grid: { container: true, spacing: 2 },
  IconButton: { children: ' ' },
  InputAdornment: { position: 'start' },
  InputLabel: { children: 'Label' },
  Link: { children: 'Link text', href: '#' },
  List: {},
  ListItem: {},
  ListItemText: { primary: 'List Item' },
  MenuItem: { children: 'Menu Item' },
  Pagination: { count: 10, page: 1 },
  Paper: { children: 'Paper content' },
  Radio: {},
  RadioGroup: { defaultValue: 'a' },
  Rating: { value: 3 },
  Select: { value: 'option1' },
  Slider: { value: 30 },
  Snackbar: { open: true, message: 'Snackbar message' },
  Stack: { spacing: 2, children: 'Stack item' },
  Switch: { checked: false },
  Tab: { label: 'Tab' },
  Table: { size: 'small' },
  TableBody: {},
  TableCell: { children: 'Cell' },
  TableHead: {},
  TableRow: {},
  TextField: { label: 'Label', placeholder: 'Placeholder' },
  ToggleButton: { value: 'value', children: 'Toggle' },
  Toolbar: { children: 'Toolbar content' },
  Tooltip: { title: 'Tooltip', children: 'Hover me' },
  Typography: { children: 'Typography text', variant: 'body1' },
};

export const getMuiDefaultArgs = (componentName) => muiDefaultArgsByComponent[componentName] || {};

export default getMuiDefaultArgs;
